program test_schema_codegen
    !! Fixed source lines are the independent oracle for type emission.

    use schema_codegen, only: schema_generate_types
    use schema_ir, only: schema_parse_text, schema_t
    implicit none

    character(len=*), parameter :: input = &
        '(schema demo (primitive bool) (primitive int) '// &
        '(record source-ref (document name) (clause name) (rule name)) '// &
        '(enum item-kind syntax constraint) '// &
        '(sum item (syntax string) constraint) (list items item) '// &
        '(optional maybe-source source-ref))'
    character(len=*), parameter :: expected_lines(*) = [character(len=256) :: &
        '! Generated by schema_codegen. Origin: MECHANICAL.', &
        'module schema_v0_generated', &
        '    integer, parameter, public :: ITEM_KIND_SYNTAX = 1', &
        '    integer, parameter, public :: ITEM_KIND_CONSTRAINT = 2', &
        '    integer, parameter, public :: ITEM_SYNTAX = 1', &
        '    integer, parameter, public :: ITEM_CONSTRAINT = 2', &
        '    type, public :: item_syntax_t', &
        '        character(len=128) :: value', &
        '    end type item_syntax_t', &
        '    type, public :: source_ref_t', &
        '        character(len=128) :: document', &
        '        character(len=128) :: rule', &
        '    type, public :: item_t', &
        '        type(item_syntax_t), allocatable :: syntax', &
        '        type(item_t), allocatable :: values(:)', &
        '        type(source_ref_t), allocatable :: value', &
        '    public :: schema_consume_source_ref', &
        '        subroutine schema_consume_source_ref_callback(value, ok, message)', &
        '    public :: schema_consume_items_elements', &
        '    subroutine schema_consume_items_elements(node, consumer, ok, message)', &
        '    subroutine schema_consume_source_ref(node, consumer, ok, message)', &
        'end module schema_v0_generated']
    character(len=256) :: message
    character(len=256) :: lines(4096)
    type(schema_t) :: schema
    logical :: ok
    integer :: count, ios, unit

    call schema_parse_text(input, schema, ok, message)
    call require(ok, message)
    open (newunit=unit, file='build/schema_v0_generated.f90', status='replace', &
        action='write', iostat=ios)
    call require(ios == 0, 'could not open generated source')
    call schema_generate_types(schema, unit, 'schema_v0_generated', ok, message)
    close (unit)
    call require(ok, message)

    call read_lines('build/schema_v0_generated.f90', lines, count)
    call require(count > 0, 'generated source is empty')
    call check_expected_lines(lines, count)

    call schema_parse_text('(schema cycle (record a (next b)) '// &
        '(record b (next a)))', schema, ok, message)
    call require(ok, message)
    open (newunit=unit, file='build/schema_cycle.f90', status='replace', action='write', &
        iostat=ios)
    call require(ios == 0, 'could not open cycle output')
    call schema_generate_types(schema, unit, 'schema_cycle', ok, message)
    close (unit)
    call require(.not. ok, 'cyclic schema was emitted')
    call require(trim(message) == 'schema has cyclic type dependencies', &
        'cyclic schema diagnostic differs')

    call check_stable_forward_dependency_order()
    call check_checked_in_generated_source()

    print '(a)', 'schema codegen test passed'

contains

    subroutine read_lines(path, values, value_count)
        character(len=*), intent(in) :: path
        character(len=*), intent(out) :: values(:)
        integer, intent(out) :: value_count
        integer :: local_ios, local_unit

        values = ''
        value_count = 0
        open (newunit=local_unit, file=path, action='read', iostat=local_ios)
        call require(local_ios == 0, 'could not reopen generated source')
        do
            if (value_count >= size(values)) call require(.false., 'generated source too long')
            read (local_unit, '(a)', iostat=local_ios) values(value_count + 1)
            if (local_ios /= 0) exit
            value_count = value_count + 1
        end do
        close (local_unit)
    end subroutine read_lines

    subroutine check_expected_lines(values, value_count)
        character(len=*), intent(in) :: values(:)
        integer, intent(in) :: value_count
        integer :: i, j
        logical :: found

        do i = 1, size(expected_lines)
            found = .false.
            do j = 1, value_count
                if (trim(values(j)) == trim(expected_lines(i))) found = .true.
            end do
            call require(found, 'expected generated line is absent')
        end do
    end subroutine check_expected_lines

    subroutine check_stable_forward_dependency_order()
        character(len=*), parameter :: ordering_input = &
            '(schema ordering (record consumer (value producer)) '// &
            '(record independent (value name)) (record producer (value name)))'
        character(len=256) :: ordering_lines(4096), ordering_message
        type(schema_t) :: ordering_schema
        logical :: ordering_ok
        integer :: ordering_count, consumer_line, independent_line, producer_line

        call schema_parse_text(ordering_input, ordering_schema, ordering_ok, ordering_message)
        call require(ordering_ok, ordering_message)
        open (newunit=unit, file='build/schema_ordering.f90', status='replace', &
            action='write', iostat=ios)
        call require(ios == 0, 'could not open ordering output')
        call schema_generate_types(ordering_schema, unit, 'schema_ordering', ordering_ok, &
            ordering_message)
        close (unit)
        call require(ordering_ok, ordering_message)
        call read_lines('build/schema_ordering.f90', ordering_lines, ordering_count)
        consumer_line = line_number(ordering_lines, ordering_count, &
            '    type, public :: consumer_t')
        independent_line = line_number(ordering_lines, ordering_count, &
            '    type, public :: independent_t')
        producer_line = line_number(ordering_lines, ordering_count, &
            '    type, public :: producer_t')
        call require(producer_line < consumer_line, &
            'forward dependency was emitted after its consumer')
        call require(consumer_line < independent_line, &
            'stable source order was lost after resolving a dependency')
    end subroutine check_stable_forward_dependency_order

    integer function line_number(values, value_count, expected) result(line)
        character(len=*), intent(in) :: values(:), expected
        integer, intent(in) :: value_count
        integer :: i

        line = 0
        do i = 1, value_count
            if (trim(values(i)) == trim(expected)) then
                line = i
                return
            end if
        end do
    end function line_number

    subroutine check_checked_in_generated_source()
        character(len=4096) :: schema_text
        character(len=256) :: fresh_lines(4096), checked_in_lines(4096)
        character(len=256) :: fresh_message
        type(schema_t) :: checked_in_schema
        integer :: fresh_count, checked_in_count, local_ios, local_unit
        logical :: fresh_ok

        open (newunit=local_unit, file='specs/schema-v0.sxs', action='read', &
            iostat=local_ios)
        call require(local_ios == 0, 'could not open schema-v0 source')
        read (local_unit, '(a)', iostat=local_ios) schema_text
        close (local_unit)
        call require(local_ios == 0, 'could not read schema-v0 source')
        call schema_parse_text(trim(schema_text), checked_in_schema, fresh_ok, fresh_message)
        call require(fresh_ok, fresh_message)

        open (newunit=local_unit, file='build/schema_v0_fresh.f90', status='replace', &
            action='write', iostat=local_ios)
        call require(local_ios == 0, 'could not open fresh schema-v0 output')
        call schema_generate_types(checked_in_schema, local_unit, 'schema_v0_generated', &
            fresh_ok, fresh_message)
        close (local_unit)
        call require(fresh_ok, fresh_message)
        call read_lines('build/schema_v0_fresh.f90', fresh_lines, fresh_count)
        call read_lines('generated/schema_v0_generated.f90', checked_in_lines, checked_in_count)
        call require(fresh_count == checked_in_count, &
            'checked-in generated schema has stale line count')
        call require(all(fresh_lines(:fresh_count) == checked_in_lines(:checked_in_count)), &
            'checked-in generated schema is stale')
    end subroutine check_checked_in_generated_source

    subroutine require(condition, failure_message)
        logical, intent(in) :: condition
        character(len=*), intent(in) :: failure_message

        if (.not. condition) then
            print '(a)', 'FAIL: '//trim(failure_message)
            stop 1
        end if
    end subroutine require

end program test_schema_codegen
