module schema_codegen
    !! Deterministically emit the first Fortran type layer from a .sxs schema.
    !!
    !! This is deliberately separate from schema parsing.  The schema remains
    !! authoritative; this module only chooses a stable source order and emits
    !! declarations marked as mechanically generated.

    use schema_ir, only: schema_declaration_t, schema_enum, schema_list, &
        schema_max_declarations, schema_optional, schema_primitive, schema_record, &
        schema_sum, schema_t, schema_validate
    implicit none
    private

    public :: schema_generate_types

contains

    subroutine schema_generate_types(schema, unit, module_name, ok, message)
        type(schema_t), intent(in) :: schema
        integer, intent(in) :: unit
        character(len=*), intent(in) :: module_name
        logical, intent(out) :: ok
        character(len=*), intent(out) :: message

        logical :: emitted(schema_max_declarations), progress
        integer :: i, emitted_count

        call schema_validate(schema, ok, message)
        if (.not. ok) return
        if (len_trim(module_name) == 0) then
            ok = .false.
            message = 'generated module name is empty'
            return
        end if
        emitted = .false.
        emitted_count = 0
        call emit_line(unit, '! Generated by schema_codegen. Origin: MECHANICAL.', ok, &
            message)
        if (.not. ok) go to 900
        call emit_line(unit, 'module '//trim(module_name), ok, message)
        if (.not. ok) go to 900
        call emit_line(unit, '    implicit none', ok, message)
        if (.not. ok) go to 900
        call emit_line(unit, '    private', ok, message)
        if (.not. ok) go to 900
        call emit_line(unit, '', ok, message)
        if (.not. ok) go to 900

        do while (emitted_count < count_emittable(schema))
            progress = .false.
            do i = 1, schema%declaration_count
                if (emitted(i)) cycle
                if (schema%declarations(i)%kind == schema_primitive) then
                    emitted(i) = .true.
                    cycle
                end if
                if (.not. declaration_ready(schema, i, emitted)) cycle
                call emit_declaration(unit, schema, i, ok, message)
                if (.not. ok) go to 900
                emitted(i) = .true.
                emitted_count = emitted_count + 1
                progress = .true.
            end do
            if (.not. progress .and. emitted_count < count_emittable(schema)) then
                ok = .false.
                message = 'schema has cyclic type dependencies'
                go to 900
            end if
        end do

        call emit_line(unit, 'end module '//trim(module_name), ok, message)

        900     continue
    end subroutine schema_generate_types

    integer function count_emittable(schema) result(count)
        type(schema_t), intent(in) :: schema
        integer :: i

        count = 0
        do i = 1, schema%declaration_count
            if (schema%declarations(i)%kind /= schema_primitive) count = count + 1
        end do
    end function count_emittable

    logical function declaration_ready(schema, index, emitted)
        type(schema_t), intent(in) :: schema
        integer, intent(in) :: index
        logical, intent(in) :: emitted(:)

        integer :: i, dependency
        character(len=128) :: type_name

        declaration_ready = .true.
        select case (schema%declarations(index)%kind)
        case (schema_record)
            do i = 1, schema%declarations(index)%member_count
                type_name = schema%declarations(index)%members(i)%type_name
                dependency = declaration_index(schema, type_name)
                if (dependency > 0) then
                    if (schema%declarations(dependency)%kind /= schema_primitive) then
                        if (.not. emitted(dependency)) declaration_ready = .false.
                    end if
                end if
            end do
        case (schema_sum)
            do i = 1, schema%declarations(index)%member_count
                type_name = schema%declarations(index)%members(i)%type_name
                if (len_trim(type_name) == 0) cycle
                dependency = declaration_index(schema, type_name)
                if (dependency > 0) then
                    if (schema%declarations(dependency)%kind /= schema_primitive) then
                        if (.not. emitted(dependency)) declaration_ready = .false.
                    end if
                end if
            end do
        case (schema_list, schema_optional)
            dependency = declaration_index(schema, schema%declarations(index)%target_type)
            if (dependency > 0) then
                if (schema%declarations(dependency)%kind /= schema_primitive) then
                    if (.not. emitted(dependency)) declaration_ready = .false.
                end if
            end if
        case default
        end select
    end function declaration_ready

    subroutine emit_declaration(unit, schema, index, ok, message)
        integer, intent(in) :: unit
        type(schema_t), intent(in) :: schema
        integer, intent(in) :: index
        logical, intent(out) :: ok
        character(len=*), intent(out) :: message

        type(schema_declaration_t) :: declaration
        character(len=256) :: line
        character(len=128) :: name, type_name, number
        integer :: i

        declaration = schema%declarations(index)
        name = fortran_identifier(declaration%name)
        ok = .true.
        message = ''
        select case (declaration%kind)
        case (schema_enum)
            do i = 1, declaration%member_count
                write (number, '(i0)') i
                line = '    integer, parameter, public :: '// &
                    trim(uppercase(name))//'_'//trim(uppercase( &
                    fortran_identifier(declaration%members(i)%name)))//' = '//trim(number)
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
            end do
        case (schema_sum)
            do i = 1, declaration%member_count
                write (number, '(i0)') i
                line = '    integer, parameter, public :: '//trim(uppercase(name))//'_'// &
                    trim(uppercase(fortran_identifier(declaration%members(i)%name)))// &
                    ' = '//trim(number)
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
            end do
            call emit_line(unit, '', ok, message)
            if (.not. ok) return
            do i = 1, declaration%member_count
                if (len_trim(declaration%members(i)%type_name) == 0) cycle
                line = '    type, public :: '//trim(name)//'_'// &
                    trim(fortran_identifier(declaration%members(i)%name))//'_t'
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
                call type_name_fortran(schema, declaration%members(i)%type_name, type_name, &
                    ok, message)
                if (.not. ok) return
                line = '        '//trim(type_name)//' :: value'
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
                line = '    end type '//trim(name)//'_'// &
                    trim(fortran_identifier(declaration%members(i)%name))//'_t'
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
                call emit_line(unit, '', ok, message)
                if (.not. ok) return
            end do
            line = '    type, public :: '//trim(name)//'_t'
            call emit_line(unit, trim(line), ok, message)
            if (.not. ok) return
            call emit_line(unit, '        integer :: kind = 0', ok, message)
            if (.not. ok) return
            do i = 1, declaration%member_count
                if (len_trim(declaration%members(i)%type_name) == 0) cycle
                line = '        type('//trim(name)//'_'// &
                    trim(fortran_identifier(declaration%members(i)%name))// &
                    '_t), allocatable :: '//trim(fortran_identifier( &
                    declaration%members(i)%name))
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
            end do
            call emit_line(unit, '    end type '//trim(name)//'_t', ok, message)
        case (schema_record)
            call emit_line(unit, '    type, public :: '//trim(name)//'_t', ok, message)
            if (.not. ok) return
            do i = 1, declaration%member_count
                call type_name_fortran(schema, declaration%members(i)%type_name, type_name, &
                    ok, message)
                if (.not. ok) return
                line = '        '//trim(type_name)//' :: '// &
                    trim(fortran_identifier(declaration%members(i)%name))
                call emit_line(unit, trim(line), ok, message)
                if (.not. ok) return
            end do
            call emit_line(unit, '    end type '//trim(name)//'_t', ok, message)
        case (schema_list)
            call type_name_fortran(schema, declaration%target_type, type_name, ok, message)
            if (.not. ok) return
            call emit_line(unit, '    type, public :: '//trim(name)//'_t', ok, message)
            if (.not. ok) return
            call emit_line(unit, '        '//trim(type_name)//', allocatable :: values(:)', &
                ok, message)
            if (.not. ok) return
            call emit_line(unit, '    end type '//trim(name)//'_t', ok, message)
        case (schema_optional)
            call type_name_fortran(schema, declaration%target_type, type_name, ok, message)
            if (.not. ok) return
            call emit_line(unit, '    type, public :: '//trim(name)//'_t', ok, message)
            if (.not. ok) return
            call emit_line(unit, '        '//trim(type_name)//', allocatable :: value', ok, &
                message)
            if (.not. ok) return
            call emit_line(unit, '    end type '//trim(name)//'_t', ok, message)
        case default
            ok = .false.
            message = 'cannot emit unknown schema declaration kind'
            return
        end select
        call emit_line(unit, '', ok, message)
    end subroutine emit_declaration

    subroutine type_name_fortran(schema, name, result, ok, message)
        type(schema_t), intent(in) :: schema
        character(len=*), intent(in) :: name
        character(len=*), intent(out) :: result
        logical, intent(out) :: ok
        character(len=*), intent(out) :: message

        integer :: index

        result = ''
        ok = .false.
        message = ''
        select case (trim(name))
        case ('bool')
            result = 'logical'
        case ('int', 'status', 'node', 'symbol', 'type', 'scope', 'name')
            result = 'integer'
        case ('string')
            result = 'character(len=128)'
        case default
            index = declaration_index(schema, name)
            if (index == 0) then
                message = 'cannot emit unknown type: '//trim(name)
                return
            end if
            if (schema%declarations(index)%kind == schema_primitive) then
                message = 'primitive type has no Fortran mapping: '//trim(name)
                return
            end if
            result = 'type('//trim(fortran_identifier(name))//'_t)'
        end select
        ok = .true.
    end subroutine type_name_fortran

    integer function declaration_index(schema, name) result(index)
        type(schema_t), intent(in) :: schema
        character(len=*), intent(in) :: name
        integer :: i

        index = 0
        do i = 1, schema%declaration_count
            if (trim(schema%declarations(i)%name) == trim(name)) then
                index = i
                return
            end if
        end do
    end function declaration_index

    function fortran_identifier(name) result(identifier)
        character(len=*), intent(in) :: name
        character(len=128) :: identifier
        integer :: i, position, code

        identifier = ''
        position = 0
        do i = 1, len_trim(name)
            code = iachar(name(i:i))
            position = position + 1
            if ((code >= iachar('a') .and. code <= iachar('z')) .or. &
                (code >= iachar('A') .and. code <= iachar('Z')) .or. &
                (code >= iachar('0') .and. code <= iachar('9')) .or. code == iachar('_')) then
                identifier(position:position) = name(i:i)
            else
                identifier(position:position) = '_'
            end if
        end do
    end function fortran_identifier

    function uppercase(text) result(result)
        character(len=*), intent(in) :: text
        character(len=128) :: result
        integer :: i, code

        result = ''
        do i = 1, len_trim(text)
            code = iachar(text(i:i))
            if (code >= iachar('a') .and. code <= iachar('z')) then
                result(i:i) = achar(code - iachar('a') + iachar('A'))
            else
                result(i:i) = text(i:i)
            end if
        end do
    end function uppercase

    subroutine emit_line(unit, text, ok, message)
        integer, intent(in) :: unit
        character(len=*), intent(in) :: text
        logical, intent(out) :: ok
        character(len=*), intent(out) :: message
        integer :: ios

        write (unit, '(a)', iostat=ios) text
        ok = ios == 0
        message = ''
        if (.not. ok) message = 'cannot write generated Fortran'
    end subroutine emit_line

end module schema_codegen
